apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cronjob
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - /bin/sh
            - -ec
            - curl http://xx.xx.xx.xx:3000
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            name: test-cronjob
            resources: {}
            terminationMessagePath: /dev/termination-l
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 1
  suspend: false
